# Running

In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn.preprocessing as prp

pd.set_option('display.max_columns', None)

train = pd.read_csv("train_dataset_hackathon_mkb.csv", delimiter = ';', encoding = 'cp1251')
test = pd.read_csv("test_dataset_hackathon_mkb.csv", delimiter = ';', encoding = 'cp1251')

print(f'shape:{train.shape}')
train.head(5)

shape:(17891, 124)

,id_contract,id_client,SIGN_DATE,IP_flag,TARGET,F1100,F1110,F1150,F1160,F1170,F1180,F1190,F1200,F1210,F1220,F1230,F1240,F1250,F1260,F1300,F1310,F1320,F1350,F1360,F1370,F1400,F1410,F1420,F1450,F1500,F1510,F1520,F1530,F1550,F1600,F1700,F2100,F2110,F2120,F2200,F2210,F2220,F2300,F2310,F2320,F2330,F2340,F2350,F2400,F2410,F1150_LAG1,F1230_LAG1,F1410_LAG1,F1510_LAG1,F1520_LAG1,F2110_LAG1,F2120_LAG1,F2200_LAG1,F2210_LAG1,F2220_LAG1,F2300_LAG1,F2320_LAG1,F2330_LAG1,F2400_LAG1,EGRPOINCLUDED,DATEFIRSTREG,OKFS_GROUP,OKOPF_GROUP,OKOGU_GROUP,OKATO_REGIONCODE,OKATO_FED,OKTMO_CODE,OKTMO_FED,WORKERSRANGE,TAXREG_REGDATE,TAXREGPAY_REGDATE,COUNTCOOWNERFCSM,COUNTCOOWNERROSSTAT,COUNTCOOWNEREGRUL,COUNTBRANCH,COUNTBRANCHROSSTAT,COUNTBRANCHEGRUL,TELEPHONECOUNT,MANAGERCOUNTINCOUNTRY,MANAGERCOUNTINREGION,MANAGERINNCOUNT,OKVED_CODE,PLAINTIFF_CASESNUMBER_YEAR,PLAINTIFF_SUM_YEAR,DEFENDANT_CASESNUMBER_YEAR,DEFENDANT_SUM_YEAR,THIRDOROTHERPERSON_YEAR,PLAINTIFF_CASESNUMBER_EVER,PLAINTIFF_SUM_EVER,DEFENDANT_CASESNUMBER_EVER,DEFENDANT_SUM_EVER,THIRDOROTHERPERSON_EVER,ADMITTEDNUMBER_233_YEAR,NOTADMITTEDNUMBER_233_YEAR,WINNERNUMBER_233_YEAR,SIGNEDNUMBER_233_YEAR,SUM_233_YEAR,ADMITTEDNUMBER_233_EVER,NOTADMITTEDNUMBER_233_EVER,WINNERNUMBER_233_EVER,SIGNEDNUMBER_233_EVER,SUM_233_EVER,ADMITTEDNUMBER_95_YEAR,NOTADMITTEDNUMBER_95_YEAR,WINNERNUMBER_95_YEAR,SIGNEDNUMBER_95_YEAR,SUM_95_YEAR,ADMITTEDNUMBER_95_EVER,NOTADMITTEDNUMBER_EVER,WINNERNUMBER_95_EVER,SIGNEDNUMBER_95_EVER,SUM_95_EVER,FLAG_DISQUALIFICATION,COUNT_CHANGE_YEAR,COUNT_CHANGE_EVER,BIRTHDATE,AGE,SEX_NAME,CITIZENSHIP_NAME
0,1,1847,01JAN2018:00:00:00,0,0,1.298961e+09,2154000.0,1.125573e+09,NaN,150010000.0,NaN,21224000.0,1.048287e+10,105901000.0,127510000.0,9.477348e+09,440671000.0,3.312980e+08,138000.0,1.960896e+09,1.000700e+07,-46634000.0,599497000.0,500000.0,1.028878e+09,340135000.0,NaN,340135000.0,NaN,9.480796e+09,2.499973e+09,6.907960e+09,NaN,NaN,1.178183e+10,1.178183e+10,2.370882e+09,5.294104e+10,5.057016e+10,631752000.0,1.083075e+09,656055000.0,8.834700e+07,NaN,106919000.0,293404000.0,1.122418e+09,1.479338e+09,3.908700e+07,-19204000.0,1.031700e+09,9.179060e+09,NaN,2.112180e+09,7.426504e+09,4.955724e+10,4.648680e+10,5.565080e+08,1.424790e+09,1.089145e+09,2.401140e+08,137626000.0,310096000.0,7.625800e+07,1.0,10AUG1993:00:00:00,Частная собственность,Коммерческая корпоративная организация,Группировки хозяйствующих субъектов и обществе...,3.0,40.0,3.701000e+09,40.0,1001 .. 5000,01JUL2006:00:00:00,01JAN1960:00:00:00,5.0,1.0,0.0,8.0,7.0,7.0,3.0,0.0,0.0,0.0,35.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,4650,01JAN2018:00:00:00,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4770,01JAN2018:00:00:00,0,0,7.337400e+07,NaN,7.337400e+07,NaN,NaN,NaN,NaN,2.161000e+07,2378000.0,NaN,1.764200e+07,1000000.0,5.530000e+05,37000.0,9.073600e+07,1.000000e+05,NaN,6780000.0,NaN,8.385600e+07,NaN,NaN,NaN,NaN,4.248000e+06,NaN,4.171000e+06,77000.0,NaN,9.498400e+07,9.498400e+07,9.315000e+06,5.218400e+07,4.286900e+07,2569000.0,NaN,6746000.0,1.190000e+06,NaN,50000.0,NaN,6.500000e+04,1.494000e+06,6.550000e+05,NaN,7.067400e+07,1.825700e+07,NaN,NaN,3.764000e+06,5.134000e+07,4.299900e+07,3.249000e+06,NaN,5.092000e+06,1.265000e+06,NaN,NaN,6.800000e+05,1.0,04FEB1992:00:00:00,Государственная собственность,Коммерческая унитарная организация,Группировки хозяйствующих субъектов и обществе...,33.0,33.0,3.371000e+10,33.0,51 .. 100,30AUG2002:00:00:00,01JAN1960:00:00:00,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,36.00.2,6.0,2762852.0,1.0,794.0,3.0,21.0,5408695.0,39.0,882647.0,4.0,1.0,0.0,1.0,1.0,1174998.0,2.0,0.0,2.0,2.0,2738217.0,38.0,0.0,38.0,39.0,4209963.0,169.0,0.0,169.0,168.0,18351739.0,NaN,NaN,1.0,NaN,NaN,NaN,NaN
3,4,12237,01JAN2018:00:00:00,0,0,1.937488e+09,122828000.0,6.103280e+08,NaN,809426000.0,356828000.0,38078000.0,5.786965e+09,12001000.0,71000.0,1.232486e+09,78603000.0,4.459193e+09,4611000.0,2.685905e+09,1.516514e+09,NaN,NaN,65834000.0,1.103557e+09,627253000.0,NaN,689000.0,626564000.0,4.411295e+09,3.930000e+05,3.092581e+09,NaN,NaN,7.724453e+09,7.724453e+09,1.694054e+10,4.028466e+10,2.334412e+10,931118000.0,1.600942e+10,NaN,1.489204e+09,263181000.0,351956000.0,5361000.0,1.283591e+09,1.335281e+09,1.102019e+09,256172000.0,5.929800e+08,1.398821e+09,NaN,2.780000e+05,3.987467e+09,3.873078e+10,2.170760e+10,1.032720e+09,1.599046e+10,NaN,1.525138e+09,323728000.0,1744000.0,1.201213e+09,1.0,01JUL2005:00:00:00,Частная собственность,Коммерческая корпоративная организация,Группировки хозяйствующих субъектов и обществе...,71.0,34.0,7.187600e+10,34.0,501 .. 1000,01JUL2005:00:00:00,01JAN1960:00:00:00,1.0,1.0,1.0,0.0,0.0,2.0,8.0,1.0,1.0,1.0,35.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,9988,01JAN2018:00:00:00,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
train.drop(['OKVED_CODE','OKTMO_CODE'], axis = 1, inplace = True)
test.drop(['OKVED_CODE','OKTMO_CODE'], axis = 1, inplace = True)

cols_many_nans = [x for x in train.columns.values if train.isnull().sum()[x] > 10000 ]
train.drop(cols_many_nans, axis = 1, inplace = True)
print(f'train_after_drop_nans_columns:{train.shape}')
test.drop(cols_many_nans, axis = 1, inplace = True)
print(f'test_after_drop_nans_columns:{test.shape}')

train_after_drop_nans_columns:(17891, 49)
test_after_drop_nans_columns:(7330, 48)

In [3]:
train.head()

,id_contract,id_client,SIGN_DATE,IP_flag,TARGET,EGRPOINCLUDED,DATEFIRSTREG,OKFS_GROUP,OKOPF_GROUP,OKOGU_GROUP,OKATO_REGIONCODE,OKATO_FED,OKTMO_FED,WORKERSRANGE,TAXREG_REGDATE,TAXREGPAY_REGDATE,COUNTCOOWNERFCSM,COUNTCOOWNERROSSTAT,COUNTCOOWNEREGRUL,COUNTBRANCH,COUNTBRANCHROSSTAT,COUNTBRANCHEGRUL,TELEPHONECOUNT,MANAGERCOUNTINCOUNTRY,MANAGERCOUNTINREGION,MANAGERINNCOUNT
0,1,1847,01JAN2018:00:00:00,0,0,1.0,10AUG1993:00:00:00,Частная собственность,Коммерческая корпоративная организация,Группировки хозяйствующих субъектов и обществе...,3.0,40.0,40.0,1001 .. 5000,01JUL2006:00:00:00,01JAN1960:00:00:00,5.0,1.0,0.0,8.0,7.0,7.0,3.0,0.0,0.0,0.0
1,2,4650,01JAN2018:00:00:00,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,4770,01JAN2018:00:00:00,0,0,1.0,04FEB1992:00:00:00,Государственная собственность,Коммерческая унитарная организация,Группировки хозяйствующих субъектов и обществе...,33.0,33.0,33.0,51 .. 100,30AUG2002:00:00:00,01JAN1960:00:00:00,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
3,4,12237,01JAN2018:00:00:00,0,0,1.0,01JUL2005:00:00:00,Частная собственность,Коммерческая корпоративная организация,Группировки хозяйствующих субъектов и обществе...,71.0,34.0,34.0,501 .. 1000,01JUL2005:00:00:00,01JAN1960:00:00:00,1.0,1.0,1.0,0.0,0.0,2.0,8.0,1.0,1.0,1.0
4,5,9988,01JAN2018:00:00:00,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Feature Engineering

In [13]:
date_columns = ['SIGN_DATE','DATEFIRSTREG','TAXREGPAY_REGDATE','TAXREG_REGDATE']
bin_columns = ['IP_flag','EGRPOINCLUDED',]
cat_columns = ['OKFS_GROUP','OKOPF_GROUP','OKOGU_GROUP','WORKERSRANGE']
real_columns = ['COUNTCOOWNERFCSM','COUNTCOOWNERROSSTAT','COUNTCOOWNEREGRUL',
        'COUNTBRANCH','COUNTBRANCHROSSTAT','COUNTBRANCHEGRUL',
       'TELEPHONECOUNT','MANAGERCOUNTINCOUNTRY','MANAGERCOUNTINREGION','MANAGERINNCOUNT']
discreate_real = ['OKATO_REGIONCODE','OKATO_FED','OKTMO_FED'] # OKTMO_CODE - just number - ignore

real_columns_F = []
for name in train.columns.values:
    if name[0] == 'F': real_columns_F.append(name)

real_columns_F_L = []
for name in train.columns.values:
    if name[0] == 'F' and name[-1] == '1': real_columns_F_L.append(name)
        
real_columns_all = real_columns + discreate_real + real_columns_F + real_columns_F_L

In [21]:
def make_date_features(data, date_columns):
    for name in date_columns:
    # the time
        data[name] = pd.to_datetime(train[name], format = '%d%b%Y:%H:%M:%S', errors = 'coerce')
        data[name + '_day'] = data[name].dt.day
        data[name + '_month'] = data[name].dt.month
        data[name + '_dayofweek'] = data[name].dt.dayofweek
        data[name + '_dayofyear'] = data[name].dt.dayofyear
    # isnull
        data['null_in_'+ name] = data[name].isnull().astype(int)
    # fill the nan
    for name in date_columns:
        data[name].fillna(data[name].mean(),inplace = True)

    # diff
    data['TAXREG_REGDATE_DATEFIRSTREG'] = (data['TAXREG_REGDATE'] - data['DATEFIRSTREG']).astype("timedelta64[D]")
    data['SIGN_DATE_DATEFIRSTREG'] = (data['SIGN_DATE'] - data['DATEFIRSTREG']).astype("timedelta64[D]")
    
    return data

def make_bin_features(data, bin_columns):
    # isnull
    for name in bin_columns:
        data['null_in_'+ name] = data[name].isnull().astype(int)
        # fill with mean()： binary to average
        data[name].fillna(data[name].mean(),inplace = True)
    return data

def make_cat_features(data, cat_columns):
    # fill with random str:
    for name in cat_columns:
        data[name].fillna('NotANumber',inplace = True)
    # OHE 
    data = pd.get_dummies(data, columns = cat_columns)
    return data

def make_real_features(data, real_columns):
    # fill with ave:
    for name in real_columns:
        data[name].fillna(data[name].mean(),inplace = True)
    # set barriers
    real_fea_map = {'COUNTCOOWNERFCSM':8 ,
               'COUNTCOOWNERROSSTAT':5,
               'COUNTCOOWNEREGRUL': 12,
               'COUNTBRANCH':7,
               'COUNTBRANCHROSSTAT':50,
               'COUNTBRANCHEGRUL':60,
               'MANAGERCOUNTINCOUNTRY':75}
    for name in real_columns:
        if name in real_fea_map:
            data[name + 'barrier'] = real_fea_map[name]
            
    # aggregation
    data['real_mean'] = data[real_columns].mean(axis=1)
    data['real_std'] = data[real_columns].std(axis=1)
    data['real_max'] = data[real_columns].max(axis=1) 
    data['real_min'] = data[real_columns].min(axis=1)
    
    # isnull
    data['null_in_'+ name] = data[name].isnull().astype(int)
    
    return data

def make_norm(data, cols):
    for name in cols:
        # data[name] = prp.StandardScaler().fit_transform(data[[name]])
        data[name] = prp.MinMaxScaler().fit_transform(data[[name]])
    return data

def make_features(data):
    # data = make_date_features(data, date_columns)
    # data = make_bin_features(data, bin_columns)
    data = make_cat_features(data, cat_columns)
    # data = make_real_features(data, real_columns)
    # data = make_real_features(data, discreate_real)
    # data = make_real_features(data, real_columns_F)
    # data = make_real_features(data, real_columns_F_L)
    data = make_norm(data, real_columns_all)
    
    return data

In [22]:
train_fe = make_features(train)
test_fe = make_features(test)
print(f'the shape of FE train: {train_fe.shape}')
train_fe.head()

the shape of FE train: (17891, 99)

,id_contract,id_client,SIGN_DATE,IP_flag,TARGET,F1200,F1210,F1230,F1250,F1300,F1500,F1520,F1600,F1700,F2110,F2120,F2200,F2300,F2350,F2400,F2410,F1230_LAG1,F1520_LAG1,F2110_LAG1,F2120_LAG1,F2200_LAG1,F2300_LAG1,F2400_LAG1,EGRPOINCLUDED,DATEFIRSTREG,OKATO_REGIONCODE,OKATO_FED,OKTMO_FED,TAXREG_REGDATE,TAXREGPAY_REGDATE,COUNTCOOWNERFCSM,COUNTCOOWNERROSSTAT,COUNTCOOWNEREGRUL,COUNTBRANCH,COUNTBRANCHROSSTAT,COUNTBRANCHEGRUL,TELEPHONECOUNT,MANAGERCOUNTINCOUNTRY,MANAGERCOUNTINREGION,MANAGERINNCOUNT,SIGN_DATE_day,SIGN_DATE_month,SIGN_DATE_dayofweek,SIGN_DATE_dayofyear,null_in_SIGN_DATE,DATEFIRSTREG_day,DATEFIRSTREG_month,DATEFIRSTREG_dayofweek,DATEFIRSTREG_dayofyear,null_in_DATEFIRSTREG,TAXREGPAY_REGDATE_day,TAXREGPAY_REGDATE_month,TAXREGPAY_REGDATE_dayofweek,TAXREGPAY_REGDATE_dayofyear,null_in_TAXREGPAY_REGDATE,TAXREG_REGDATE_day,TAXREG_REGDATE_month,TAXREG_REGDATE_dayofweek,TAXREG_REGDATE_dayofyear,null_in_TAXREG_REGDATE,TAXREG_REGDATE_DATEFIRSTREG,SIGN_DATE_DATEFIRSTREG,null_in_IP_flag,null_in_EGRPOINCLUDED,OKFS_GROUP_NotANumber,OKFS_GROUP_Государственная собственность,OKFS_GROUP_Иностранная собственность,OKFS_GROUP_Смешенная российская собственность,OKFS_GROUP_Совместная российская и иностранная собственность,OKFS_GROUP_Частная собственность,OKOPF_GROUP_NotANumber,OKOPF_GROUP_Без прав юридического лица,OKOPF_GROUP_Коммерческая корпоративная организация,OKOPF_GROUP_Коммерческая унитарная организация,OKOPF_GROUP_Некоммерческая корпоративная организация,OKOPF_GROUP_Некоммерческая унитарная организация,OKOGU_GROUP_NotANumber,OKOGU_GROUP_Государственная власть в РФ,OKOGU_GROUP_Государственная власть в субъектах РФ,OKOGU_GROUP_Группировки хозяйствующих субъектов и общественных объединений,OKOGU_GROUP_Местное самоуправление в РФ,WORKERSRANGE_0 .. 5,WORKERSRANGE_1001 .. 5000,WORKERSRANGE_101 .. 150,WORKERSRANGE_11 .. 15,WORKERSRANGE_151 .. 200,WORKERSRANGE_16 .. 50,WORKERSRANGE_201 .. 250,WORKERSRANGE_251 .. 500,WORKERSRANGE_5000 и более,WORKERSRANGE_501 .. 1000,WORKERSRANGE_51 .. 100,WORKERSRANGE_6 .. 10,WORKERSRANGE_NotANumber
0,1,1847,2018-01-01,0,0,0.060156,0.002388,0.073823,0.005094,0.075725,0.052319,0.074923,0.008268,0.008268,0.159829,0.241350,0.076939,0.060246,0.028489,0.065807,0.526101,0.067913,0.080562,0.153052,0.221569,0.086369,0.066986,0.066080,1.000000,1993-08-10 00:00:00.000000000,0.020408,0.833333,0.833333,2006-07-01 00:00:00.000000000,1960-01-01 00:00:00.000000000,0.098039,0.0,0.000000,0.070175,0.005627,0.066038,0.006508,0.000000,0.000000,0.000000,1,1,0,1,0,10.0,8.0,1.0,222.0,0,1.0,1.0,4.0,1.0,0,1.0,7.0,5.0,182.0,0,4708.0,8910.0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0
1,2,4650,2018-01-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900702,2010-11-18 12:32:39.485414144,NaN,NaN,NaN,2011-11-22 11:41:28.292859648,1967-02-10 16:58:03.010386928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,368.0,2600.0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1
2,3,4770,2018-01-01,0,0,0.000126,0.000058,0.000137,0.000312,0.074056,0.000044,0.000056,0.000067,0.000067,0.000158,0.000733,0.070736,0.059663,0.010558,0.065525,NaN,0.000158,0.000069,0.000159,0.000303,0.080187,0.065399,0.065525,1.000000,1992-02-04 00:00:00.000000000,0.326531,0.250000,0.250000,2002-08-30 00:00:00.000000000,1960-01-01 00:00:00.000000000,0.000000,0.0,0.002075,0.000000,0.000000,0.000000,0.002169,0.005682,0.016393,0.014286,1,1,0,1,0,4.0,2.0,1.0,35.0,0,1.0,1.0,4.0,1.0,0,30.0,8.0,4.0,242.0,0,3860.0,9463.0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0
3,4,12237,2018-01-01,0,0,0.033209,0.000275,0.009600,0.064773,0.076373,0.024354,0.033548,0.005421,0.005421,0.121619,0.111696,0.079890,0.069613,0.026741,0.073613,0.536635,0.010369,0.043269,0.119616,0.103517,0.091691,0.075526,0.074342,1.000000,2005-07-01 00:00:00.000000000,0.714286,0.333333,0.333333,2005-07-01 00:00:00.000000000,1960-01-01 00:00:00.000000000,0.019608,0.0,0.002075,0.000000,0.000000,0.018868,0.017354,0.005682,0.016393,0.014286,1,1,0,1,0,1.0,7.0,4.0,182.0,0,1.0,1.0,4.0,1.0,0,1.0,7.0,4.0,182.0,0,0.0,4567.0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4,5,9988,2018-01-01,1,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.900702,2010-11-18 12:32:39.485414144,NaN,NaN,NaN,2011-11-22 11:41:28.292859648,1967-02-10 16:58:03.010386928,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,1,0,1,0,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,NaN,NaN,NaN,NaN,1,368.0,2600.0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1

## Random Forest

In [23]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

label_col = 'TARGET'
features_cols = train.drop(['TARGET'], axis='columns').select_dtypes(include=[np.number]).columns.tolist()

In [9]:
# TUNING FOR n_estimators = 80
param_test1 = {'n_estimators':range(10,100,10)}
gsearch1 = GridSearchCV(estimator = RandomForestClassifier(min_samples_split=100,
                                  min_samples_leaf=20,max_depth=8,max_features='sqrt' ,random_state=10), 
                       param_grid = param_test1, scoring='roc_auc',cv=5)
gsearch1.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch1.best_params_, gsearch1.best_score_

({'n_estimators': 80}, 0.8171163203498917)

In [10]:
param_test1 = {'n_estimators':range(70,90,10)}
gsearch1 = GridSearchCV(estimator = RandomForestClassifier(min_samples_split=100,
                                  min_samples_leaf=20,max_depth=8,max_features='sqrt' ,random_state=10), 
                       param_grid = param_test1, scoring='roc_auc',cv=5)
gsearch1.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch1.best_params_, gsearch1.best_score_

({'n_estimators': 80}, 0.8171163203498917)

In [11]:
# TUNING FOR max_depth, min_samples_split = 13, 30

param_test2 = {'max_depth':range(3,14,2), 'min_samples_split':range(50,201,20)}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 80, 
                                  min_samples_leaf=20,max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test2, scoring='roc_auc', cv=5)
gsearch2.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch2.best_params_, gsearch2.best_score_

({'max_depth': 13, 'min_samples_split': 70}, 0.837631787957864)

In [14]:
param_test2 = {'max_depth':range(15,30,2), 'min_samples_split':range(10,50,5)}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 80, 
                                  min_samples_leaf=20,max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test2, scoring='roc_auc', cv=5)
gsearch2.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch2.best_params_, gsearch2.best_score_

({'max_depth': 21, 'min_samples_split': 10}, 0.8430215183160475)

In [21]:
param_test2 = {'min_samples_split':range(10,50,5)}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 80, max_depth = 18,
                                  min_samples_leaf=20,max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test2, scoring='roc_auc', cv=5)
gsearch2.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch2.best_params_, gsearch2.best_score_

({'min_samples_split': 10}, 0.892348973805238)

In [22]:
param_test2 = {'min_samples_split':range(5,15,1)}
gsearch2 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 80, max_depth = 21,
                                  min_samples_leaf=20,max_features='sqrt' ,oob_score=True, random_state=10),
   param_grid = param_test2, scoring='roc_auc', cv=5)
gsearch2.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch2.best_params_, gsearch2.best_score_

({'min_samples_split': 5}, 0.892348973805238)

In [16]:
# TUNING FOR min_samples_leaf, max_features = 9, 7

param_test3 = {'min_samples_leaf':range(1,5,1), 'max_features':range(1,5,1)}
gsearch3 = GridSearchCV(estimator = RandomForestClassifier(n_estimators= 80, max_depth = 21,
                                  min_samples_split=10 ,oob_score=True, random_state=10),
   param_grid = param_test3, scoring='roc_auc', cv=5)
gsearch3.fit(train_fe[features_cols].fillna(0), train_fe[label_col])
gsearch3.best_params_, gsearch3.best_score_

({'max_features': 3, 'min_samples_leaf': 2}, 0.8670479680584553)

### using tuned params

In [28]:
train_fe.shape

(17891, 99)

In [24]:
# use tuned paras
rf = RandomForestClassifier(n_estimators = 80, max_depth = 13, min_samples_split = 30, min_samples_leaf = 9, max_features = 7, n_jobs = -1)

cv_baseline_score = cross_val_score(rf, train_fe[features_cols].fillna(0), train_fe[label_col], cv=5, scoring='roc_auc').mean()
print(f'roc_auc_score: {cv_baseline_score}')

rf.fit(train_fe[features_cols].fillna(0), train_fe[label_col])

roc_auc_score: 0.8926601391003999

RandomForestClassifier(max_depth=13, max_features=7, min_samples_leaf=9,
                       min_samples_split=30, n_estimators=80, n_jobs=-1)

In [25]:
test['TARGET'] = rf.predict_proba(test_fe[features_cols].fillna(0))[:, 1]

test[['id_contract', 'TARGET']].to_csv('submit_file_rf_fe_9.csv', sep=';', index=False)
test[['id_contract', 'TARGET']].head()

   id_contract    TARGET
0        17892  0.147307
1        17893  0.235888
2        17894  0.195839
3        17895  0.327876
4        17896  0.302807